### ISSUE TITLE
There are some opcode definitions missing here vs Sapphire. Is it intended because they are not used?

### ISSUE THREAD

**Issue by collett8192** [karashiiro/FFXIVOpcodes#21]
If not I'll PR an update adding missing ones from Sapphire which are still being maintained.

**Comment by karashiiro** [comment]
To make it easier to keep this updated, I don't strictly require that people keep outdated opcodes commented out on the repo, if that's what you're noticing, just because it's tedious to comment out all of the old ones each patch. We do have plenty of updated opcodes that aren't used, so if Sapphire has any updated ones we don't have, I'd welcome them.

**Comment by collett8192** [comment]
Sapphire is mostly manual updating till latest patch (5.45 hotfix). While they're updated now, they're most likely not going to be updated any time fast next patch. If commenting out old opcode is the way to go here than just keeping it until updated like Sapphire I guess I'll update only existing ones.
